name: Run chat script
on:
  schedule:
    - cron: '*/60 * * * *' # Run every 60 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
      - name: Run chat script
        run: python app.py
      - name: Upload JSON file
        uses: actions/upload-artifact@v2
        with:
          name: conversation_history
          path: conversation_history.json
